### ISSUE TITLE
what is the  "unique" and "all" means ?

### ISSUE THREAD

**Issue by ArtemisZGL** [facebookresearch/covost#1]
Hello, thanks for your great work. According to the train, dev, test tsv file in the CV dataset, it's equal to the unique number in the table. But what the all number of sentence means ?

**Comment by kahne** [comment]
@ArtemisZGL 

In Common Voice, same sentences can be spoken by different speakers. "Unique" refers to the number of unique sentences and "all" refers to duplicated sentences considering multiple speakers.

**Comment by ArtemisZGL** [comment]
@kahne Thanks for your reply, I should read the paper more carefully.

**Comment by Rajul01** [comment]
Thankyou. This is a great contribution in SLT. I would request the authors to kindly check the get_covost_splits.py or a possible reason why the splits obtained for CoVoST version 1 contain several entries in a single cell (checked only for French and Spanish data). Please have a look at the attachment. 
[Splits.zip](https://github.com/facebookresearch/covost/files/5877780/Splits.zip)

**Comment by kahne** [comment]
> Thankyou. This is a great contribution in SLT. I would request the authors to kindly check the get_covost_splits.py or a possible reason why the splits obtained for CoVoST version 1 contain several entries in a single cell (checked only for French and Spanish data). Please have a look at the attachment.
> [Splits.zip](https://github.com/facebookresearch/covost/files/5877780/Splits.zip)

Thanks. Can you be a bit more specific? What does "single cell" refer to?

**Comment by Rajul01** [comment]
"Single cell" refers to the entries present in a particular row and column in the .tsv file. In the attached files ("Splits.zip") for eg. please check the cell in covost.fr_en.train.tsv  corresponding to the "translation" column, and row number "13124" , which contains several entries in one cell.

**Comment by jmp84** [comment]
@Rajul01 I downloaded Splits.zip attached above and ran this command on covost.fr_en.train.tsv: `cat covost.fr_en.train.tsv  | awk -F"\t" '{print NF}' | sort -u` which gives 4 so the number of columns for each row is 4. Would you be able to clarify what you mean by "several entries in one cell." ? I checked line 13124 and didn't notice anything wrong with the format:

common_voice_fr_18092563.mp3	Cours Tolstoï au numéro vingt-six	Tolstoï courtyard, at number twenty-six.	4c667af1608c767c19e5912eb6c6dc7c80c8474eda12a4db88b9d9645ebec71504587708236f2f7d8e10b1634694b5389a997c3746b6277e4d075949ace40090
