### ISSUE TITLE
Could you build a mirror for China IPs?

### ISSUE THREAD

**Issue by zjw1990** [facebookresearch/covost#2]
Dear team,

The downloading process is really slow in China, and I used the Ip proxys abroad and it is easily baned by Amazon. I am wondering whther you have any other mirros&locations in China?

Thanks

**Comment by kahne** [comment]
Hi @zjw1990 , the speech data is from Common Voice and we currently don't have a plan for redistributing it. You may reach out to Common Voice for the ask: https://commonvoice.mozilla.org/en.
